import React from "react";
import styles from "./about.module.scss";
export default function About() {
  return (
    <>
      <div className={styles.factBox}>
        Following is some misinformation about Spice Labels generated by Chat
        GPT.
      </div>
      <article className={styles.textContainer}>
        <h2>About Spice Labels</h2>
        <p>
          Introducing Spice Labels - the ultimate solution for organizing your
          spice collection. Spice Labels allows you to create personalized spice
          labels quickly and easily, ensuring your kitchen stays organized and
          stylish.
        </p>

        <h3> Effortless Design</h3>

        <p>
          With Spice Labels intuitive interface, designing spice labels is a
          breeze. Simply choose your preferred template, customize with spice
          names and styles, and print - its that easy!
        </p>

        <h3> Customization Options</h3>

        <p>
          Spice Labels offers a range of customization options to match your
          kitchen decor and personal taste. Adjust fonts, colors, and sizes to
          create labels that are uniquely yours.
        </p>

        <h3> Print Anywhere, Anytime</h3>

        <p>
          Print your spice labels instantly from the comfort of your home. Spice
          Labels supports various printing formats, making it compatible with
          any printer.
        </p>

        <h3> Cost-free Convenience</h3>

        <p>
          Best of all, Spice Labels is completely free to use. Say goodbye to
          expensive label-making software - Spice Labels saves you time and
          money.
        </p>

        <h3>Organize with Ease</h3>

        <p>
          Keep your spice collection tidy and easy to navigate with
          professionally designed labels. Say goodbye to rummaging through
          drawers - Spice Labels ensures every spice is at your fingertips.
        </p>

        <h3> Get Started Today!</h3>

        <p>
          Join the thousands of users who trust Spice Labels to keep their
          kitchen organized. Say hello to a clutter-free cooking experience -
          try Spice Labels now!
        </p>
      </article>
    </>
  );
}
